FROM debian:bookworm

RUN apt-get update


RUN apt-get install -y ca-certificates curl gnupg

RUN install -m 0755 -d /etc/apt/keyrings

RUN  curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg \
     && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable" \
     > /etc/apt/sources.list.d/docker.list

RUN apt-get update

RUN apt-get install -y docker-ce-cli

RUN apt install python3 python3-pip python3-venv -y

RUN apt-get install -y openssh-server

RUN rm -rf /var/lib/apt/lists/*

RUN mkdir /run/sshd \
    && echo 'root:password' | chpasswd \
    && sed -i 's/#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
